"""Create durable reconciliation and publication tables.

Revision ID: 004_reconciliation_publication
Revises: 003_entity_resolution
"""

from __future__ import annotations

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql


revision = "004_reconciliation_publication"
down_revision = "003_entity_resolution"
branch_labels = None
depends_on = None


MONEY = sa.Numeric(precision=18, scale=2)


def upgrade() -> None:
    op.create_table(
        "reconciliation_run",
        sa.Column(
            "run_id",
            postgresql.UUID(as_uuid=True),
            primary_key=True,
            server_default=sa.text("gen_random_uuid()"),
        ),
        sa.Column(
            "contract_version",
            sa.String(length=32),
            nullable=False,
        ),
        sa.Column(
            "as_of_utc",
            sa.DateTime(timezone=True),
            nullable=False,
        ),
        sa.Column(
            "input_watermark_utc",
            sa.DateTime(timezone=True),
            nullable=False,
        ),
        sa.Column(
            "status",
            sa.String(length=16),
            nullable=False,
            server_default=sa.text("'CANDIDATE'"),
        ),
        sa.Column(
            "result_hash",
            sa.String(length=64),
            nullable=False,
        ),
        sa.Column(
            "created_at_utc",
            sa.DateTime(timezone=True),
            nullable=False,
            server_default=sa.text("CURRENT_TIMESTAMP"),
        ),
        sa.Column(
            "published_at_utc",
            sa.DateTime(timezone=True),
            nullable=True,
        ),
        sa.Column(
            "failure_reason",
            sa.Text(),
            nullable=True,
        ),
        sa.CheckConstraint(
            """
            status IN (
                'CANDIDATE',
                'PUBLISHED',
                'FAILED'
            )
            """,
            name="ck_reconciliation_run_status",
        ),
        sa.CheckConstraint(
            "result_hash ~ '^[0-9a-f]{64}$'",
            name="ck_reconciliation_run_result_hash_sha256",
        ),
        sa.CheckConstraint(
            """
            status <> 'PUBLISHED'
            OR published_at_utc IS NOT NULL
            """,
            name="ck_reconciliation_run_published_timestamp",
        ),
        sa.CheckConstraint(
            """
            status <> 'FAILED'
            OR failure_reason IS NOT NULL
            """,
            name="ck_reconciliation_run_failure_reason",
        ),
    )

    op.create_table(
        "transaction_reconciliation",
        sa.Column(
            "run_id",
            postgresql.UUID(as_uuid=True),
            nullable=False,
        ),
        sa.Column(
            "order_id",
            sa.String(length=128),
            nullable=False,
        ),
        sa.Column(
            "order_status",
            sa.String(length=32),
            nullable=False,
        ),
        sa.Column(
            "currency",
            sa.String(length=3),
            nullable=False,
        ),
        sa.Column(
            "expected_collection",
            MONEY,
            nullable=False,
        ),
        sa.Column(
            "captured_total",
            MONEY,
            nullable=False,
        ),
        sa.Column(
            "collection_variance",
            MONEY,
            nullable=False,
        ),
        sa.Column(
            "successful_refund_total",
            MONEY,
            nullable=False,
        ),
        sa.Column(
            "expected_fee_total",
            MONEY,
            nullable=False,
        ),
        sa.Column(
            "reported_fee_total",
            MONEY,
            nullable=False,
        ),
        sa.Column(
            "lifetime_net_collection",
            MONEY,
            nullable=False,
        ),
        sa.Column(
            "captured_payment_count",
            sa.Integer(),
            nullable=False,
        ),
        sa.Column(
            "successful_refund_count",
            sa.Integer(),
            nullable=False,
        ),
        sa.Column(
            "state",
            sa.String(length=16),
            nullable=False,
        ),
        sa.Column(
            "exception_codes",
            postgresql.JSONB(),
            nullable=False,
            server_default=sa.text("'[]'::jsonb"),
        ),
        sa.PrimaryKeyConstraint(
            "run_id",
            "order_id",
            name="pk_transaction_reconciliation",
        ),
        sa.ForeignKeyConstraint(
            ["run_id"],
            ["reconciliation_run.run_id"],
            name="fk_transaction_reconciliation_run",
            ondelete="RESTRICT",
        ),
        sa.CheckConstraint(
            "currency = 'EUR'",
            name="ck_transaction_reconciliation_currency",
        ),
        sa.CheckConstraint(
            """
            state IN (
                'RECONCILED',
                'INCOMPLETE',
                'EXCEPTION'
            )
            """,
            name="ck_transaction_reconciliation_state",
        ),
        sa.CheckConstraint(
            "captured_payment_count >= 0",
            name="ck_transaction_payment_count_nonnegative",
        ),
        sa.CheckConstraint(
            "successful_refund_count >= 0",
            name="ck_transaction_refund_count_nonnegative",
        ),
    )

    op.create_table(
        "payout_reconciliation",
        sa.Column(
            "run_id",
            postgresql.UUID(as_uuid=True),
            nullable=False,
        ),
        sa.Column(
            "payout_id",
            sa.String(length=128),
            nullable=False,
        ),
        sa.Column(
            "payout_date",
            sa.Date(),
            nullable=False,
        ),
        sa.Column(
            "currency",
            sa.String(length=3),
            nullable=False,
        ),
        sa.Column(
            "expected_payout",
            MONEY,
            nullable=False,
        ),
        sa.Column(
            "reported_line_total",
            MONEY,
            nullable=False,
        ),
        sa.Column(
            "reported_net_amount",
            MONEY,
            nullable=False,
        ),
        sa.Column(
            "provider_report_variance",
            MONEY,
            nullable=False,
        ),
        sa.Column(
            "end_to_end_payout_variance",
            MONEY,
            nullable=False,
        ),
        sa.Column(
            "expected_movement_count",
            sa.Integer(),
            nullable=False,
        ),
        sa.Column(
            "settlement_line_count",
            sa.Integer(),
            nullable=False,
        ),
        sa.Column(
            "state",
            sa.String(length=16),
            nullable=False,
        ),
        sa.Column(
            "exception_codes",
            postgresql.JSONB(),
            nullable=False,
            server_default=sa.text("'[]'::jsonb"),
        ),
        sa.PrimaryKeyConstraint(
            "run_id",
            "payout_id",
            name="pk_payout_reconciliation",
        ),
        sa.ForeignKeyConstraint(
            ["run_id"],
            ["reconciliation_run.run_id"],
            name="fk_payout_reconciliation_run",
            ondelete="RESTRICT",
        ),
        sa.CheckConstraint(
            "currency = 'EUR'",
            name="ck_payout_reconciliation_currency",
        ),
        sa.CheckConstraint(
            """
            state IN (
                'RECONCILED',
                'INCOMPLETE',
                'EXCEPTION'
            )
            """,
            name="ck_payout_reconciliation_state",
        ),
        sa.CheckConstraint(
            "expected_movement_count >= 0",
            name="ck_payout_expected_count_nonnegative",
        ),
        sa.CheckConstraint(
            "settlement_line_count >= 0",
            name="ck_payout_line_count_nonnegative",
        ),
    )

    op.create_table(
        "reconciliation_exception",
        sa.Column(
            "exception_id",
            sa.BigInteger(),
            sa.Identity(start=1),
            primary_key=True,
        ),
        sa.Column(
            "run_id",
            postgresql.UUID(as_uuid=True),
            nullable=False,
        ),
        sa.Column(
            "rule_id",
            sa.String(length=128),
            nullable=False,
        ),
        sa.Column(
            "exception_type",
            sa.String(length=64),
            nullable=False,
        ),
        sa.Column(
            "entity_type",
            sa.String(length=32),
            nullable=False,
        ),
        sa.Column(
            "entity_id",
            sa.String(length=128),
            nullable=False,
        ),
        sa.Column(
            "expected_amount",
            MONEY,
            nullable=True,
        ),
        sa.Column(
            "actual_amount",
            MONEY,
            nullable=True,
        ),
        sa.Column(
            "variance",
            MONEY,
            nullable=True,
        ),
        sa.Column(
            "detected_at_utc",
            sa.DateTime(timezone=True),
            nullable=False,
        ),
        sa.Column(
            "status",
            sa.String(length=16),
            nullable=False,
        ),
        sa.Column(
            "supporting_source_record_ids",
            postgresql.JSONB(),
            nullable=False,
            server_default=sa.text("'[]'::jsonb"),
        ),
        sa.ForeignKeyConstraint(
            ["run_id"],
            ["reconciliation_run.run_id"],
            name="fk_reconciliation_exception_run",
            ondelete="RESTRICT",
        ),
    )

    op.create_table(
        "source_completeness_snapshot",
        sa.Column(
            "run_id",
            postgresql.UUID(as_uuid=True),
            nullable=False,
        ),
        sa.Column(
            "report_type",
            sa.String(length=32),
            nullable=False,
        ),
        sa.Column(
            "report_date",
            sa.Date(),
            nullable=False,
        ),
        sa.Column(
            "state",
            sa.String(length=16),
            nullable=False,
        ),
        sa.Column(
            "deadline_utc",
            sa.DateTime(timezone=True),
            nullable=False,
        ),
        sa.Column(
            "observed_at_utc",
            sa.DateTime(timezone=True),
            nullable=False,
        ),
        sa.Column(
            "issue_codes",
            postgresql.JSONB(),
            nullable=False,
            server_default=sa.text("'[]'::jsonb"),
        ),
        sa.PrimaryKeyConstraint(
            "run_id",
            "report_type",
            "report_date",
            name="pk_source_completeness_snapshot",
        ),
        sa.ForeignKeyConstraint(
            ["run_id"],
            ["reconciliation_run.run_id"],
            name="fk_source_completeness_run",
            ondelete="RESTRICT",
        ),
        sa.CheckConstraint(
            """
            state IN (
                'COMPLETE',
                'PENDING',
                'INCOMPLETE'
            )
            """,
            name="ck_source_completeness_state",
        ),
    )

    op.create_table(
        "publication_pointer",
        sa.Column(
            "publication_name",
            sa.String(length=64),
            primary_key=True,
        ),
        sa.Column(
            "current_run_id",
            postgresql.UUID(as_uuid=True),
            nullable=False,
        ),
        sa.Column(
            "updated_at_utc",
            sa.DateTime(timezone=True),
            nullable=False,
            server_default=sa.text("CURRENT_TIMESTAMP"),
        ),
        sa.ForeignKeyConstraint(
            ["current_run_id"],
            ["reconciliation_run.run_id"],
            name="fk_publication_pointer_run",
            ondelete="RESTRICT",
        ),
    )


def downgrade() -> None:
    op.drop_table("publication_pointer")
    op.drop_table("source_completeness_snapshot")
    op.drop_table("reconciliation_exception")
    op.drop_table("payout_reconciliation")
    op.drop_table("transaction_reconciliation")
    op.drop_table("reconciliation_run")